### ISSUE TITLE
Support for battery level

### ISSUE THREAD

**Issue by doktoil-makresh** [sighmon/raspberry-pi-bluetooth-temperature#1]
Hi,

I can see from your readme and comment on intructables.com that you found a way to retrieve the battery level. 
Can you please detail which bytes are the ones to get data from?

**Comment by sighmon** [comment]
@doktoil-makresh I didn't ever get around to trying to add the battery level to the script, and don't have a device with me to test it on, but here's an attempt if you want to try it: https://github.com/sighmon/raspberry-pi-bluetooth-temperature/pull/2

**Comment by doktoil-makresh** [comment]
Hi Simon, thank you for answering quickly!

It seems to work. I guess I'm receiving battery level for the main station. 
Do you have any idea or documentation that may help retrieving sensors batteries ?
I was expecting to find sensors batteries in other indexes, but there are no other indexes.

**Comment by sighmon** [comment]
@doktoil-makresh Unfortunately I don't have any documentation... and just out of interest, was your reading `64%` by any chance? I couldn't get it to return anything other than that when I was using `sudo gatttool -b <BLE ADDRESS> -t random --char-read --uuid=0x2A19` to read it. So I wonder if they haven't implemented it for this device?

I also wonder if we haven't signed up for notifications from the battery uuid, and if we have whether the readings are in the bytes we're not handling. e.g. this line in the output: `handle 1d = 11120b11112927ff00800080ffffffffffffffff`

**Comment by doktoil-makresh** [comment]
gatttool outputs 64 indeed, but not your piece of script.
I tried extracting data from the different handlers, but I don't know what too expect: percentage, quarters (the app shows from 0 to 3 bars), voltage, etc
Without any documentation it is a bit difficult. I'll work on it as soon as one of my sensor battery is not shown as full in the app, and I hope finding something...

Thanks again for your help.
